package backup

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"

	"golang.org/x/crypto/curve25519"
	"golang.org/x/crypto/nacl/box"
)

// Asymmetric backup encryption via NaCl sealed boxes (X25519 +
// XSalsa20-Poly1305 — libsodium's crypto_box_seal). The server config holds
// only the recipient PUBLIC key, so a server or bucket-credential compromise
// cannot decrypt historical backups; that needs the matching PRIVATE key,
// generated by GenerateKeypair and kept OFFLINE by the operator.
//
// (We use x/crypto — already a dependency — rather than filippo.io/age: same
// asymmetric guarantee, no extra module, and decryption only ever happens via
// this binary's `restore` subcommand anyway, so age-CLI interop buys nothing.)
//
// Key format: base64-std of the 32-byte X25519 key. Public = recipient,
// private = identity.

// GenerateKeypair returns a fresh (publicKey, privateKey) pair, base64-encoded.
// The public key goes in config (backup.recipient_pubkey); the private key is
// stored offline and supplied to `restore` only during disaster recovery.
func GenerateKeypair() (pub string, priv string, err error) {
	pk, sk, err := box.GenerateKey(rand.Reader)
	if err != nil {
		return "", "", err
	}
	return base64.StdEncoding.EncodeToString(pk[:]), base64.StdEncoding.EncodeToString(sk[:]), nil
}

func parseKey32(s string) (*[32]byte, error) {
	raw, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		return nil, fmt.Errorf("base64 decode key: %w", err)
	}
	if len(raw) != 32 {
		return nil, fmt.Errorf("key must be 32 bytes, got %d", len(raw))
	}
	var k [32]byte
	copy(k[:], raw)
	return &k, nil
}

// sealTo encrypts plaintext to the recipient public key (base64). Output is a
// self-contained sealed box (embeds an ephemeral sender key + auth tag).
func sealTo(plaintext []byte, recipientPub string) ([]byte, error) {
	pub, err := parseKey32(recipientPub)
	if err != nil {
		return nil, fmt.Errorf("recipient pubkey: %w", err)
	}
	sealed, err := box.SealAnonymous(nil, plaintext, pub, rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("seal: %w", err)
	}
	return sealed, nil
}

// openFrom decrypts a sealed box with the identity private key (base64).
func openFrom(sealed []byte, identityPriv string) ([]byte, error) {
	priv, err := parseKey32(identityPriv)
	if err != nil {
		return nil, fmt.Errorf("identity privkey: %w", err)
	}
	// SealAnonymous/OpenAnonymous need the recipient's PUBLIC key too; derive
	// it from the private key (X25519 scalar-basepoint mult).
	pubRaw, err := curve25519.X25519(priv[:], curve25519.Basepoint)
	if err != nil {
		return nil, fmt.Errorf("derive pubkey: %w", err)
	}
	var pub [32]byte
	copy(pub[:], pubRaw)
	plain, ok := box.OpenAnonymous(nil, sealed, &pub, priv)
	if !ok {
		return nil, fmt.Errorf("decrypt failed: wrong key or corrupt backup")
	}
	return plain, nil
}
